/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a05b8865-798f-47fd-b80e-cf0d80dd340d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DuhJAuXpZ",
    "aws_user_pools_web_client_id": "2ps2t8a53qvochnc07mfi85o6p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nqn2chwxzfh5pi7rcn2736rf6a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "6156e7dbe7c3425eb9fd1312de66057b",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
